### ISSUE TITLE
list - minor display issues

### ISSUE THREAD

**Issue by flatcap** [guyzmo/git-repo#114]
The output of the "list" command has the escape sequence `^[[?25` (reveal cursor) at the end.
Is this intentional?  If so, please can you disable it when the output is redirected?

The output of the "list -l" command isn't all sent to the same output stream.
The header is send to stderr, the body to stdout.

**Comment by guyzmo** [comment]
> The output of the "list" command has the escape sequence ^[[?25 (reveal cursor) at the end.
Is this intentional? If so, please can you disable it when the output is redirected?

I'm not sure, IIRC the reveal cursor was to fix an issue with the progress bar widget. Sure I'll check.

> The output of the "list -l" command isn't all sent to the same output stream.
> The header is send to stderr, the body to stdout.

that's on purpose, to avoid having to drop header upon redirection, a `2>&1` is easier than `tail -n +2`.  Though I could simply not print the header if in a redirect. What is your use case, so I can think about it?

**Comment by flatcap** [comment]
> > The header is send to stderr, the body to stdout.

> that's on purpose, to avoid having to drop header upon redirection

Oh, OK.  I don't think I know of any other programs that do that.

I was just saving a list of repos to a file.
I think I'd rather delete a header than redirect stderr.
If something goes wrong with git-repo, **that** should be on stderr, where I can see it.

**Comment by guyzmo** [comment]
an alternative would be a `-q` or `--batch` option to suppress colours and headers. But that would mean also keeping headers in stdout.

**Comment by guyzmo** [comment]
cf attached PR:

- removed the ceveal cursor character when not outputing in a terminal (`sys.stdout.isatty() FTW)
- made headers not appearing when not in a terminal (again)

and a bit of internal cooking 😉

**Comment by flatcap** [comment]
Thanks
