### ISSUE TITLE
No support for gitlab subgroups.

### ISSUE THREAD

**Issue by AmandaCameron** [guyzmo/git-repo#174]
I've got a private gitlab instance which makes pretty heavy use of the [subgroup feature](https://docs.gitlab.com/ce/user/group/subgroups/)  added in GitLab 9.0, as a result I can't use this tool to clone, make a MR, etc for a repo that's in a subgroup (or, even a subgroup of a subgroup).

**Comment by guyzmo** [comment]
oh my… I did not know about that feature 😮 

currently the code base is definitely not supporting subgroups, as the logic recognizing repo slugs is common to all services. So with a quick look (and remembering), I think that the culprits are:

- [this one, that extracts the slug from a full URI](https://github.com/guyzmo/git-repo/blob/devel/git_repo/repo.py#L208,L223)
- [that bit that also does conversion](https://github.com/guyzmo/git-repo/blob/devel/git_repo/services/service.py#L84,L94), 
- maybe [that one as well, that convert them back](https://github.com/guyzmo/git-repo/blob/devel/git_repo/services/service.py#L270,L293)

I was already thinking of calling `username` part of the slug more properly `namespace` (that would cover the idea of subgroups) and remove the one slash constraint (which is not a technical constraint), when working on 2.0. But I guess gitlab has decided otherwise.

Sadly, I'm currently having 2 jobs at the same time, which does not leave me much time to actually work on this any time soon, but I'd be very happy to help anybody willing to jump on this! I'm always connected on IRC/Matrix/Gitter cf the Readme.

**Comment by timofonic** [comment]
@guyzmo What about promoting this project and giving commit access to trusted people? I'm totally sure your tool can be quite interesting to tons of other projects, but there's not enough awareness of it.

**Comment by guyzmo** [comment]
You're welcome to discuss all that on IRC, `irc.freenode.org` / `#git-repo`. My status is that currently I'm totally snowed, having worked the last 3 months day in, day out, week ends included… And that project has lesser priority. I'd be happy to give commit access to trusted people, but it looks like I've not been good enough at creating a community around the tool! ☹
