### ISSUE TITLE
Fatal error: 'GitRepoRunner' object has no attribute 'target'

### ISSUE THREAD

**Issue by nikitavbv** [guyzmo/git-repo#185]
I have been using `git-repo` for a while and I noticed that quite often it fails to clone a repository.
It outputs:
```
Fatal error: 'GitRepoRunner' object has no attribute 'target'
```
The thing is that if you try running command again - it may fail again. Or work. This was totally random, but luckily I managed to figure it out.

To start with, `git-repo` uses `KeywordArgumentParser` to parse command line params. It iterates over all args using `for arg, value in self.args.items()`. However, we need to remember that `self.arg.items()` is not ordered. So we process args in random order. 
Because of that, sometimes we process `<namespace>/<repo>` parameter before `<target>` parameter, sometimes after. And in cases when we process `<namespace>/<repo>` before `<target>` we have the issue.
`<namespace>/<repo>` arg is proccessed by `set_repo_slug` in `repo.py`. This function uses `self.target` value: `service = RepositoryService.get_service(None, self.target)`. And that's the problem. If the `<target>` was not parsed before `<namespace>/<repo>` we get an error here.

So there are two possible solutions:
1. Change `set_repo_slug` so it doesn't use `self.target` anywhere.
2. Ensure somehow that `<target>` is always processed before `<namespace>/<repo>`

Note: The problem occurs on python3.5 and below only. There are no problem on python3.6 as dictionaries are ordered there

**Comment by mtfurlan** [comment]
Thank you for your nice description of the problem.
I can confirm this issue with python 3.5.3, and using 3.7.1 it has not happened again.

**Comment by guyzmo** [comment]
Hm… weirdly I don't have that issue on the travis runner tests on py ≤3.5.

I remember having had this problem at some point in the past, and I'm not sure whether it's been solved since, or if it's still a thing. But as we're getting away from py3.5, with soon py3.8 being released.

So I'll close this as won't solve, and I hope it won't bite us again in the future.

If this happens again, I believe the best solution would be to indeed force `<target>` parsing before the loop to avoid the race condition.
