### ISSUE TITLE
GitLab gitrepo doesn't work with self-hosted instance

### ISSUE THREAD

**Issue by gkaklas** [guyzmo/git-repo#36]
I wanted to setup a custom gitlab service, so I edited my `.gitconfig` to include the following section:

```
[gitrepo "selfhosted"]
        fqdn = mygitlab.example.org
        type = gitlab
        token = SUPER_SECRET
```

Then when I tried to create a repo I got a "401 Unauthorized" error. I generated a new token just in case it was wrong but that didn't seem to be the problem... I also made sure my instance's GitLab API was working by testing it with curl etc.

Then I thought that maybe git-repo tries to authenticate with another server, so I changed the personal token from my instance to a one generated for my gitlab.com account, and it worked (the repository was created on gitlab.com).

So even when specifying an `fqdn` in the config file, git-repo still tries to communicate with the default GitLab server, gitlab.com. With the appropriate `.gitconfig`, gitlab.com and github work fine though.

I should also state that I tried both the latest version from pypi and the master branch and the issue remains.

**Comment by guyzmo** [comment]
Thank you for reporting this!

I need to figure what went wrong! I have to admit I did not write regression tests for the self-hosted instances, because doing so would be too much of a pain to setup… So there's a good chance I introduced a regression at some point.

I'll take a look at this as soon as I can!

**Comment by guyzmo** [comment]
ok, I just tested and I definitely replicate that issue with my own configuration and copy of the code (in case there was any doubt). I'm pretty sure it's a fairly simple issue to dig in!

**Comment by guyzmo** [comment]
FYI, I'm baking a patch… Still running some tests, but I'll land this the soonest I can ☺

**Comment by grugnog** [comment]
Happy to help test

**Comment by davewongillies** [comment]
:-1:
Doesn't work for me :cry: 
```
→ git gl request ls
List of open requests to merge:
 id	title                                                       	URL
Fatal error: 
```
I've got this in my `~/.gitconfig`

```
[gitrepo "gl"]
    token = <my secret token>
    type = gitlab
    fqdn = my.gitlab.instance
```

I've tried both personal access tokens and a private token and neither work.

**Comment by guyzmo** [comment]
oh… I'm sorry but the gitlab merge requests are still WIP, I haven't finished writing tests for it. I'll publish it along with the snippets (gitlab's gists) in 1.8.

You can check the status of the development over here on the [features/gitlab-gist-requests branch](https://github.com/guyzmo/git-repo/tree/features/gitlab-gists-requests), and I'm reporting progress within the issue #12 .

Basically, MR are implemented, Snippets have a rough support (I'm currently working on a patch for gitlab's API to expose the global snippets, so we can use those instead of the per-project snippets).

And once it's finished, I'll have to write all the tests for those features.
