### ISSUE TITLE
Remove dependency on amoffat/sh

### ISSUE THREAD

**Issue by masaeedu** [guyzmo/git-repo#37]
This project would be quite useful on Windows machines, and I can't imagine any of the code is inherently tied to OS/X or Linux. If the dependency on https://github.com/amoffat/sh were eliminated it would be possible to install this on Windows as well.

**Comment by guyzmo** [comment]
hum… I actually never noticed it was using that dependency ☺

After a quick lookup, it looks like it's a dependency of the [SheepRider/BitBucket-api](https://github.com/SheepRider/Bitbucket-api) library. 
It looks like it's only required for running [the tests](https://github.com/Sheeprider/BitBucket-api/blob/master/bitbucket/tests/private/repository.py#L6).

So a good solution would be to send a PR to SheepRider in order to remove the dependency enforcement upon install, but only for tests, in [setup.py](https://github.com/Sheeprider/BitBucket-api/blob/master/setup.py#L20) and in [requirements.txt](https://github.com/Sheeprider/BitBucket-api/blob/master/requirements.txt#L3).

I'm opening an issue for that on the other repository.

**Comment by guyzmo** [comment]
The issue will soon be solved, though, because AFAICT bitbucket plans on switching to a new API using swagger to self describre and generate the lib automagically, making bitbucket-api useless.

**Comment by guyzmo** [comment]
Please check that it's working fine installing it from the PR **before** installing `git-repo`:

```
pip install git+https://github.com/SheepRider/BitBucket-api.git@pull/25/#egg=bitbucket-api
pip install git-repo
```

if the first install goes well, when installing git-repo, it will resolve that bitbucket-api is already installed and won't try to pull it again from pypi.

**Comment by guyzmo** [comment]
ok, so far, I'll take that no news is good news on this and I'll close the issue.

Otherwise, I'm planning on switching to another bitbucket library that's still maintained and should make this issue get away. 🤞

**Comment by CurtisLusmore** [comment]
Just wanted to add that I tested this on Windows, although I couldn't install `BitBucket-api` from the pull request branch - I had to go to your branch directly.

```
pip install git+https://github.com/guyzmo/BitBucket-api.git@separate-tests-deps#egg=bitbucket-api
pip install git-repo
```

**Comment by guyzmo** [comment]
I'll try to figure out a way to make it easier for windows users, though beware *there be dragons*, as I don't have a windows machine and I did not setup a CI for windows.

**Comment by masaeedu** [comment]
@guyzmo Could the install-from-fork-of-bitbucket-api-branch approach you're describing here be documented in the README?

**Comment by guyzmo** [comment]
@masaeedu I'm working on the next version of git-repo (v1.9) that will feature `pybitbucket`, with no more dependency problem for windows users, and with all the missing features (including retrieval of the private key!).

So I don't think this would be necessary, as the situation is temporary. I hope to release 1.9 in the next couple of weeks.

**Comment by masaeedu** [comment]
@guyzmo Yeah, just saw that issue. Awesome work!
