### ISSUE TITLE
Crashes because of overly specific gitpython dependency

### ISSUE THREAD

**Issue by phihag** [guyzmo/git-repo#40]
I installed git-repo using `sudo pip3 install git-repo` on a debian sid x64 system. However, upon launching it crashes:
```
$ git repo config
Traceback (most recent call last):
  File "/usr/local/bin/git-repo", line 7, in <module>
    from git_repo.repo import cli
  File "/usr/local/lib/python3.5/dist-packages/git_repo/repo.py", line 112, in <module>
    __version__ = pkg_resources.require('git-repo')[0].version
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 970, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 861, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (GitPython 2.0.8 (/home/phihag/.local/lib/python3.5/site-packages), Requirement.parse('GitPython==2.0.6'), {'git-repo'})
```

I have GitPython 2.0.8 installed since I need it for various other projects. The [changes in 2.0.8](http://gitpython.readthedocs.io/en/stable/changes.html) are all fixes of annoying bugs. Why do I need to downgrade my GitPython installation to a buggy one in order to use git-repo?

**Comment by guyzmo** [comment]
thank you for reporting this. I actually had to overconstraint the version because (cf #30) gitpython made my builds fail because of a few buggy versions they released, the issue being with uritemplate that changed names and they did a huge hack with pip to make it work.

I have to unconstraint it a bit to make sure that it's now fine. I'll check that and if it's ok, I'll do a patch!

**Comment by guyzmo** [comment]
I'm now testing with a newer gitpython 🤞
