### ISSUE TITLE
Not working with relative URL gitlab instance

### ISSUE THREAD

**Issue by feigaoxyz** [guyzmo/git-repo#57]
``` gitconfig
[gitrepo "iitserver"]
    type = gitlab
    token = TOP_SECRET
    fqdn = iitserver/gitlab
```

Results for `git repo iitserver clone user/project -vvv`
https://gist.github.com/feigaoxyz/94edd2c4844f53403f7cb163109d98e5

I can access the server old styles like `git clone http://iitserver/gitlab/user/project.git` or `git clone git@iitserver:user/project.git`.

Is it because I deployed the instance to `http` not `https`?

**Comment by guyzmo** [comment]
hum… The problem at hand has nothing to do with http vs https — even though I'm not sure it's going to work on a non-https server — it's because git-repo has not been designed for gitlab instances running within a path of an existing domain. Actually, even the configuration option makes it clear `fqdn` meaning *fully qualified domain name*, otherwise I'd have used `URL`.

Actually, installing on a relative URL is not even encouraged by the gitlab documentation:

> [*While it is recommended to install GitLab in its own (sub)domain, sometimes this is not possible due to a variety of reasons. In that case, GitLab can also be installed under a relative URL, for example https://example.com/gitlab.*](https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-a-relative-url-for-gitlab)

That being said, it's not *impossible* to change, and we could try to find a way around that. But my main issue would be the assymetry between the git URL and the HTTPS URL to access a given project. That means complicating substancially the code to fix a very specific non-recommended way of installing gitlab.

So, let me ask you: what's preventing you from installing your instance as `://gitlab.iitserver` instead of `://iitserver/gitlab`?

---------------

About the `http` vs `https` issue, that's another issue and if really is a need, I guess it'd be possible to add support for that. But to be honest, we're in 2016 and configuring HTTPS on a server is as easy as adding three lines to a configuration and running a copy/pasted command. So to follow up on *that* topic, please open a new issue.

**Comment by feigaoxyz** [comment]
@guyzmo 

Hi, thanks for the information. I could not remember exactly why I did that so I made some experiments just earlier today. The results are

- external_url "http://gitlab.iitserver" is not working
- external_url "http://iitserver" is working
- external_url "http://iitserver/gitlab" is working

I don't know exactly why the first one is not working, (at least I didn't see it on [gitlab doc](https://docs.gitlab.com/omnibus/settings/configuration.html).)

**Comment by guyzmo** [comment]
the first one should be working, I'll try reproducing it and see whether it can be confirmed as a bug, but it really should'nt.

**Comment by guyzmo** [comment]
@feigaoxyz any updates on that bug?

**Comment by feigaoxyz** [comment]
@guyzmo 
I have settled with existing solution "http://hostname" and did not explore further.
