### ISSUE TITLE
Is the version in requirements.txt mandatory?

### ISSUE THREAD

**Issue by luckynum7** [guyzmo/git-repo#61]
Hi,

I'm making an archlinux PKGBUILD for git-repo. However the `requirements.txt` claim for certain version of those dependencies.

Is the version in requirements.txt mandatory, or the requirements can be greater than or equal to (>=)?

Thank you for your time.

**Comment by guyzmo** [comment]
Hi!

thank you for doing it, I'm also an arch user (though I don't install python packages from AUR, I prefer using pip directly).

In the `requirements.txt`, not all requirements are mandatory, but some are. Here's a detail.

Those two have a pretty stable API, and I'm not expecting them to break the build anytime soon, so it should be ok.

```
docopt
progress==1.2
```

That one got unmaintained, so with all the dust there's on the 0.5, it's safe to make less constrained… But there's no impact on leaving it as is ☺

```
bitbucket-api==0.5.0
```

GitPython [burnt my build once](https://github.com/guyzmo/git-repo/issues/40), but since 2.0.6 it should be ok.

```
GitPython>=2.0.6
```

As gitlab is planning a major change in the API, there are chances that this one might break soon (or maybe it might support both version of the API…). Though I just ran a test, and they all are 👌 with 0.16.

```
python-gitlab==0.13
```

Though, those two shall be kept as is, because [`uritemplate.py` changed name recently into `uritemplate` and `github3.py` is pointing to `uritemplate.py` not `uritemplate`](https://github.com/sigmavirus24/github3.py/issues/634#issuecomment-247755392). I believe that with the next major version (I guess 1.0.0), `github3.py` will point to `uritemplate` and then we should be safe. 

```
uritemplate.py==2.0.0
github3.py==0.9.5
```

as a conclusion, I might change to:

```
docopt
progress
bitbucket-api>=0.5.0
GitPython>=2.0.6
python-gitlab>=0.13
uritemplate.py==2.0.0
github3.py==0.9.5
```

**Comment by luckynum7** [comment]
Hi,

Since there is an enhancement #43, `bitbucket-api==0.5.0` should be good.

Those two, I can wait until the upgrade. Thanks a lot.
```
uritemplate.py==2.0.0
github3.py==0.9.5
```
