### ISSUE TITLE
Store tokens somewhere other than ~/.gitconfig

### ISSUE THREAD

**Issue by colemickens** [guyzmo/git-repo#63]
I keep `~/.gitconfig` stored in source control. I can't do so with git-repo storing the github auth token in there...

Thanks.

**Comment by guyzmo** [comment]
I have had a thought about it, how would you feel about having credentials stored in ~/.netrc which look like a place commonly used for credentials…

@colemickens any opinion on that?

**Comment by colemickens** [comment]
Seems reasonable to me.

**Comment by guyhughes** [comment]
@colemickens you could also use set `include.path` in your gitconfig to include a untracked file, like [this](https://github.com/guyhughes/dots/blob/master/git/.gitconfig#L168).

**Comment by guyzmo** [comment]
hm… @guyhughes did not know about that, but if it's actually working (we need to test that!), I guess this would be a case for not changing the credential storage mechanism, meaning less work for me ☺

@colemickens any opinions on that?

**Comment by guyzmo** [comment]
I actually tested this, and it's working like a charm. 👍

So won't implement a .netrc option, and make a documentation about this feature.

**Comment by guyzmo** [comment]
I've added a small utility that actually extract all `gitrepo ".*"` sections into a new file, and automatically replaces them with a `include.path` item. I've info about that to the README file in the configuration section.

Hope it covers the issue ☺

**Comment by m040601** [comment]
Thanks for your effort providing an alternative to having the tokens written in .gitconfig

But this still doesnt solve the issue that git-repo still assumes a .gitconfig must exist, or else it will force me to create one.


I want to choose to use $HOME/.git/config/ for my git configuration
I do not want any other tool to force me to create that .gitconfig file in my system.
I do not want to have includes in a .gitconfig file pointing somewhere else.

I simply do not want that .gitconfig file to exist.

This is possible because git, like many other programs nowadays follow the XDG specifications.
https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
https://wiki.archlinux.org/index.php/XDG_user_directories


Would it be possible to either:

a) just simply don't force me to create or look for a .gitconfig file. Just look for .config/git/config
b) create or use a $HOME/.config/git-repo/config (and eventually $HOME/.config/git-repo/tokens etc ...)

Thanks in advance !

**Comment by guyhughes** [comment]
Using the XDG directory, the git-config supported path is `$XDG_CONFIG_HOME/git/config`. 

Git began fully implementing support for config files in `$XDG_CONFIG_HOME` fairly recently in v2.4.3. Here's the commit:
https://github.com/git/git/commit/ea19289bc82351b7ac20ea2fd877e2bdde97ae34

This is a new feature request. So I'll open a new issue.

**Comment by guyzmo** [comment]
thank you @guyhughes ☺

**Comment by guyzmo** [comment]
thank you for that well documented comment, @m040601, but as @guyhughes it's better fitted as a new issue.
