### ISSUE TITLE
Automatically add remote when forking

### ISSUE THREAD

**Issue by graingert** [guyzmo/git-repo#72]

**Comment by guyzmo** [comment]
that's a good thing, but there's many usecases to take care of:

* when forking from within a repository (`git x fork` or `git x fork name/proj`)
  * if there's an `x` remote,
   * if `x` remote is the same as the given (or guessed) slug, switch it to `upstream` remote
   * if it's not, do nothing and raise an error about this
  * if there's no 'x' remote, make the argument slug `upstream` remote
* when forking from outside a repository
 * either do nothing, or `clone` as a new repository. Maybe could be handled through an argument?

**Comment by graingert** [comment]
The workflow I use from `hub` is:

```
hub clone some/repo
git checkout -b "some-branch"
vim some_edits.py
git commit -m "some commit"
hub fork
git push -fu graingert
hub pull-request
```

and I'd like to be able to do the same thing with git-repo with the same, if not fewer steps.

**Comment by graingert** [comment]
So I suppose that `git x fork` should just fork the repo to a given user/project (or the current user) and assign it to the remote named for that user.

**Comment by graingert** [comment]
ideally `git repo fork` should be able to work out that I'm in a GitHub/BitBucket/GitLab from a specific host and just do the right thing.

**Comment by guyzmo** [comment]
> ideally git repo fork should be able to work out that I'm in a repo cloned from GitHub/BitBucket/GitLab from a specific host and just do the right thing.

well, first there's a `repo_slug` detection mechanism implemented from the `.git/config` remotes, so that should be partially covered. Even though some mechanism should be made to make sure we're forking on the same host, not across hosts.

> The workflow I use from hub is:

That's about the same worklfow I have, even though there's an extra step you're right should be getting rid of. But as I said, we cannot only implement a side of it, it needs to work consistenly in all cases…

> Eg, I'm only interested in the in-git fork workflow.

And what about `fork`ing into another namespace you're member of? that should be taken care of as well… So actually there's an extra use case to add: `git x fork another_namespace`.

**Comment by guyzmo** [comment]
As said on IRC, what you want is actually what the code is already supposed to be doing, cf [the source code](https://github.com/guyzmo/git-repo/blob/master/git_repo/services/service.py#L297,L321)

So you might have nailed an edge case that I did not test properly for, and need to be fixed and tested.

Could you give me a proper example of when it's not behaving the way it's supposed to?

**Comment by graingert** [comment]
ah I see it creates the remote under "graingert"

**Comment by graingert** [comment]
I'd rather this used `<username>` and `origin`
