### ISSUE TITLE
Automatically grab pull request title and body from commit log.

### ISSUE THREAD

**Issue by graingert** [guyzmo/git-repo#73]
When running `git repo hub request` without a title pre-fill a GIT_EDITOR window with:

```
The first line of the first commit message between source and destination branches

The rest of the commit messages between source and destination branches
```

like the [hub](https://hub.github.com/) command

**Comment by guyzmo** [comment]
hm… that's a good idea, like it ☺

**Comment by graingert** [comment]
@guyzmo I'm looking for an exact replica of the "hub" command that also supports GitLab and potentially bitbucket.

**Comment by graingert** [comment]
This project seems the closest, but I've added two issues for the big UI changes I need.

**Comment by guyzmo** [comment]
wel, TBH I'm not looking to mimic the API of the `hub` command which I'm not an user of, but I'm happy to take any good ideas ☺

If you want to do some PR, I'd be happy to help guide you through the codebase to make it simple for you. I've been slow on new implementations (because lately work and health did not give me enough time for it), and the implementations I'm caring are for getting gitlab/bitbucket integrations on par with the github features.

N.B.: you can join me on IRC on freenode if you like that, I'm `zmo` there.

**Comment by graingert** [comment]
@guyzmo I've pinged you on freenode.
