### ISSUE TITLE
Support for http and non-standard ports

### ISSUE THREAD

**Issue by pyhedgehog** [guyzmo/git-repo#81]
1. If one starts gitlab (or i.e. gogs) on localhost there are no need for SSL in transfer.
 2. Locally started service can be listening on ports other that 80/443 and 22 for ssh. I.e. gogs by default listens on 3000.

There are several places (at least [repo.py:178](https://github.com/guyzmo/git-repo/blob/5bbee93dcd4a948a5c57dae82155cf2476b5aee8/git_repo/repo.py#L178) where assumed https.

**Comment by guyzmo** [comment]
Yup, you're right, I shouldn't have assumed `https` only per default. 

I only introduced recently insecure (i.e. self signed) certificate supports, and it's quite likely that specifiying non-standard ports might break URL lookup. Though there really is only two places where `https` is assumed, and one of those two where a change is really needed by a PR fixing this issue:

* it's [`_guess_repo_slug()`](https://github.com/guyzmo/git-repo/blob/808af79745bcd007a873c0ba206005644d6204fd/git_repo/repo.py#L178,L178), I guess there you could check a `service.protocol` that would contain `https`, the same way you can check for `service.name` etc… That would be doing a proper decoupling of the protocol the same way I've been doing with the other elements.

The other place is:

* in [`url_ro`](https://github.com/guyzmo/git-repo/blob/808af79745bcd007a873c0ba206005644d6204fd/git_repo/services/service.py#L169,L172) which can be overloaded when subclassing the class `RepositoryService`, so it's less an issue. But still a good idea to keep in coherence with the change I'm suggesting above.

Otherwise, that shouldn't impact the tests, and neither should it impact implementation of the other services.
