### ISSUE TITLE
Support self-signed certification

### ISSUE THREAD

**Issue by pyhedgehog** [guyzmo/git-repo#88]
PR #76 has a wrong implementation of `requests.Session().verify` value, which can be either boolean or reference to certificate to verify server against.

**Comment by guyzmo** [comment]
I'm quite ok with PR #76 implementation (which made it to v1.8). 

But I'd be happy to see it improved with the configuration accepting a file path to the certificate. If anybody needs it, I'm accepting a PR for that, otherwise I consider that rather low priority and I'll care about that at around v1.10 or after.
