### ISSUE TITLE
Unhandled formatting error when create merge request on github

### ISSUE THREAD

**Issue by Bubu** [guyzmo/git-repo#92]
Following the documentation I wanted to create a merge request on github. doing `git hub request curl/curl create 'some title'` from with the current branch I want to create the merge request from.
I get the following error: 
`Fatal error: Unhandled formatting error: [{'resource': 'PullRequest', 'code': 'invalid', 'field': 'head'}]`

It works when not specifying any user/repo. But then it creates the MR in my fork which is not what I wanted.

Using version 1.8.0 from Pypi

**Comment by guyzmo** [comment]
I have recently also noticed I messed things up, last time I tried to push a request. It definitely was working in 1.7 or 1.6, so I very likely introduced a regression, and it means the tests I wrote are not good enough (but this feature is quite hard to test).

It took me some time to realise this went south, because I too often do P/M requestss directly on the repository that shall receive the request. 😖

I'm planning a new release very soon with bitbucket integration (the code is ready, I'm just waiting for python-bitbucket to make a new release with necessary changes I pushed) and I'll try to get back on this issue for 1.9 or 1.9.x!

**Comment by guyzmo** [comment]
I believe the issue is very simple, yet very hard to catch, it being just a mix up between the parameters I'm extracting from the commandline (or the current repo), and the API request made to the remote server.

**Comment by Bubu** [comment]
@guyzmo Thanks for working on this btw!

I thought of something else related to this: Would it be possible to refer to the upstream repo by a symbolic name when creating push requests?
Like so: `git hub request upstream create 'some title'`, where upstream is the git remote pointing to the repo I forked from.
Or is this already possible?

**Comment by guyzmo** [comment]
well, I'd appreciate to keep one issue→one topic, to make things easier to track. 

> Would it be possible to refer to the upstream repo by a symbolic name when creating push requests?

Though about the API, it's not designed that way, and I'm still not convinced I found the right UX for it… but I'm not sure your suggestion is the right way either.

Right now, per default I believe it's taking the current branch's remote, which is wrong (and why it's sending the PR to yourself), but it's supposed to lookup the current repository's `upstream` remote if there is one and make the PR there, and fallback to the `github` remote (or `gitlab`/`bitbucket` dependending on the `target` in the command) if there's no `upstream` remote — the `upstream` is being created by the `fork` command).

Then to define the target to another repository instead of the `upstream` you shall provide the repo slug of that repository.

Please, if you want to talk further about this, open a new issue though ☺
