### ISSUE TITLE
Request subcommand should target upstream remote by default.

### ISSUE THREAD

**Issue by Bubu** [guyzmo/git-repo#94]
As discussed here https://github.com/guyzmo/git-repo/issues/92#issuecomment-272165984 git repo should target the upstream remote by default. (I agree it's the simplest solution)

Right now it seems to work always against my fork, even when I'm doing a `git hub request list` on the master branch. (Which's upstream is origin, which == upstream.)

**Comment by guyzmo** [comment]
I've had a little thought about this, and here's how I think `git XXX request` shall behave:

```
git XXX request create "title" [--message="message"]
```

* create a new request of the current branch on the current repository's parent fork's main branch, as registered on the service.
* If current repository is not a fork, use it instead.
* If the branch hasn't been pushed (yet), throw an error.

```
git XXX request create <branch> "title" [--message="message"]
```

* create a new request of the given branch `<branch>` on the current repository's parent fork's main branch, as registered on the service.
* If current repository is not a fork, use it instead.
* If the branch hasn't been pushed (yet), throw an error.

```
git XXX request create <branch> <onto> "title" [--message="message"]
```

* create a new request of the given branch `<branch>` on the current repository's parent fork's given `<onto>` branch, as registered on the service.
* If current repository is not a fork, use it instead.
* If the branch hasn't been pushed (yet), throw an error.

```
git XXX request <user/repo> create [<branch> [<onto>]]  "title" [--message="message"]
```

* same as above, but instead of using current repository's parent fork (or current repository as fallback), use given repository `<user/repo>`.
