### ISSUE TITLE
Support gitconfig in XDG directory

### ISSUE THREAD

**Issue by guyhughes** [guyzmo/git-repo#95]
Git began fully implementing support for config files in $XDG_CONFIG_HOME fairly recently in v2.4.3. Here's the commit:
git/git@ea19289

Using the XDG directory, the git-config supported path is `$XDG_CONFIG_HOME/git/config`,  and if the environment variable is undefined it ought to default to `$HOME/.config`. 

@m040601 requested this feature. 
https://github.com/guyzmo/git-repo/issues/63#issuecomment-273290534

I'd be interested in implementing.

**Comment by guyzmo** [comment]
ok, two tasks are needed:

- check and avoid any reference to `$HOME/.gitconfig` [in the sources](https://github.com/guyzmo/git-repo/search?utf8=✓&q=".gitconfig")
- have the [gitpython-developers/GitPython] abstraction provide us with the right path.

what I believe is that it's not `git-repo`'s role to decide where the configuration is.

[gitpython-developers/GitPython]:https://github.com/gitpython-developers/GitPython

**Comment by guyzmo** [comment]
looking further, the impact seems to located mostly in two use cases of the applications:

- when working outside of a repository, then the `.gitconfig` path is resolved using [a hardcoded `$HOME/.gitconfig`](https://github.com/guyzmo/git-repo/blob/f36a4d0f7b187ca9211665fe10bc8921ef8358c1/git_repo/repo.py#L276,L276), otherwise it uses `gitpython` to resolve the full configuration of the current repository ;
- when running `git-repo config` which defaults to ['$HOME/.gitconfig'](https://github.com/guyzmo/git-repo/blob/f36a4d0f7b187ca9211665fe10bc8921ef8358c1/git_repo/repo.py#L276,L276), but can be overridden with the `--config` option.

**Comment by guyzmo** [comment]
sorry for not having left you the change to do it, but I went over that part of the code and just did it. 
Though it's not a thorough implementation and it'll ignore the system part. It's just a hardcoded precedence. It might be improvable, but rather 👌 as is 😉

Please test the devel branch, I'm going to release it early next week (I'm waiting on new release of pybitbucket and that FOSDEM is over… whichever comes first 😉)
