### ISSUE TITLE
Issue count is wrong in "ls -l"

### ISSUE THREAD

**Issue by flatcap** [guyzmo/git-repo#96]
Currently, this repo has 22 issues and 5 pull requests.
However, `git hub ls -l guyzmo` shows 27 issues:
```
Status	Commits	Reqs	Issues	Forks	Coders	Watch	Likes	Lang	Modif		Name
  	304	5	27	29	11	666	666	Python	Jan 16 20:43	guyzmo/git-repo
```
GitHub's issue count includes the pull requests.

(I'd offer a PR, but I don't speak python)

**Comment by guyzmo** [comment]
technically speaking PR are issues for github, though it wouldn't be hard to make issues-reqs where that happens.

But the `ls -l` feature will need some sort of rewrite, as currently it's hammering the github API to get the needed data, and after a dozen repositories it's just breaking because the requests are being throttled ☹
